remote_theme: pmarsceill/just-the-docs

# Auxiliary links for the upper right navigation.
aux_links:
  "External link described in `/docs/_config.yml`. Use for GitHub link":
    - "//github.com"
  "Campbell Muscle Lab Home Page":
    - "//campbell-muscle-lab.github.io"

# Not a big fan of dark mode. I think the light looks better.
# color_scheme: "dark"

# You can display an image instead of the site's title like this.
# logo: "/assets/images/example-image.png"

# Footer
footer_content: "Written by the Campbell Muscle Lab"

# This is the title of the website
title: "Website Title in _config.yml"